name = "Black & Light"
license = "GNU3.0"
licenselink = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
tags = ["responsive", "minimal", "simple", "personal", "white"]
features = []
min_version = 0.17

[author]
  name = "David Hamp-Gonsalves"
  homepage = "https://davidhampgonsalves.com"
